name: Tests

on: [push, pull_request]

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [7.2, 7.3]
        steps:
            -   uses: actions/checkout@v1
            -   name: composer
                run: composer update --no-progress
            -   name: execute unit tests
                run: Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -x
            -   run: |
                    COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} \
                        .build/bin/php-coveralls \
                        --verbose
    acceptance-tests:
        runs-on: ubuntu-latest
        steps:
            - run: curl -L https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | sudo bash
            - run: ddev start
